Send HTTP event with JUnit report
allegro-actions/junit-reporter pull request #71
Opened 2021-05-21 10:20 UTC by jjusianiec

2021-05-21 10:43 UTC, deejay1 requested changes

2021-05-21 10:43 UTC, deejay1 commented on action.yml
> +    default: 'https://c.allegrogroup.com/qyn1owR'
maybe do not put private addresses here? ;)

2021-05-21 10:46 UTC, deejay1 submitted a review, later dismissed

2021-05-21 11:11 UTC, m1chu-alle submitted a review, later dismissed

2021-05-21 11:30 UTC, arti-allegro submitted a review, later dismissed

2021-05-24 15:26 UTC, alleGregT approved these changes

2021-05-24 15:26 UTC, deejay1 approved these changes

2021-05-24 15:26 UTC, alleGregT approved these changes

2021-05-24 15:26 UTC, alleGregT approved these changes

2021-05-24 15:27 UTC, alleGregT approved these changes

2021-05-25 06:00 UTC, arti-allegro approved these changes

2021-05-25 07:02 UTC, merged